/*
 * DB SCHEMAS v0.1.0
 */

--CREATE DATABASE mydb;

--\c mydb

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------
-- version
-- --------------------------------------------------------
-- Contains a single row with this databases sql schema version
-- Doing it here to keep it generic between databases in case of a switch (eg MariahDB)
-- --------------------------------------------------------

CREATE TABLE "version" (
  "schema" TEXT NOT NULL
);

insert into "version" ("schema") values ('0.1.0');

-- --------------------------------------------------------
-- users
-- --------------------------------------------------------

CREATE TABLE "users" (
  "userid" TEXT NOT NULL PRIMARY KEY,
  "email" TEXT NOT NULL,
  -- hashed and salted - generated by the website
  "password" TEXT NOT NULL,
  "name" TEXT NOT NULL
);


CREATE TABLE "user_status" (
  "userid" TEXT NOT NULL PRIMARY KEY REFERENCES "users"("userid") ON DELETE CASCADE,
  "userStatus" TEXT NOT NULL,
  "createdDate" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- --------------------------------------------------------
-- statistics
-- --------------------------------------------------------

CREATE TABLE "global_stats" (
  "appName" TEXT NOT NULL PRIMARY KEY,
  "stats" JSONB NOT NULL
);
